### ISSUE TITLE
Build takes 30 mins

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy-wasm#10]
`bazel test //test/...` takes 30 minutes on 16 core 64GB machine. It would be good be able to scope to opt-out of some of the complex build pieces in CI and normal development. We need bazel options to be able to select it out.

**Comment by PiotrSikora** [comment]
See https://github.com/envoyproxy/envoy-wasm/pull/1

**Comment by PiotrSikora** [comment]
Fixed in #1.
