### ISSUE TITLE
Add inBound / outBound enum to config

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy-wasm#102]
Most / All WASM filters require inbound / outbound configuration.

This should be hoisted into the filter config.
We should add a message as [a peer of](https://github.com/envoyproxy/envoy-wasm/blob/master/api/envoy/config/wasm/v2/wasm.proto#L38) `string configuration=4`  message. This message can be shared with the plugin implementations. 
At present the message should contain only an enum `TrafficDirection   INBOUND, OUTBOUND, BOTH?` 

```
message PluginConfig {
  // Indicates whether the module in running on inbound or outbound filter chain.
  enum Direction {
    INBOUND = 0;
    OUTBOUND = 1;
  }
  Direction direction = 1;

// others later ...
}
```

**Comment by mandarjog** [comment]
@kyessenov @jplevyak

**Comment by kyessenov** [comment]
I'm adding it as a native config in LDS. We could swap the implementation in the WASM binding once that becomes available.

**Comment by kyessenov** [comment]
The LDS change was merge. It's available as factory context direction().

**Comment by jplevyak** [comment]
https://github.com/envoyproxy/envoy-wasm/pull/122

**Comment by kyessenov** [comment]
This is available in xDS and ABI.
/close
