### ISSUE TITLE
Add emscripten support into Bazel

### ISSUE THREAD

**Issue by bianpengyuan** [envoyproxy/envoy-wasm#108]
Right now all WASM files are pre generated and checked in. It would be nice to have emscripten support with bazel so that
* the wasm could be generated during test time, to prevent them out of sync.
* Null plugin uses bazel to build, and the same build system should be used to generate the WASM module file for those plugins.

https://docs.bazel.build/versions/master/tutorial/cc-toolchain-config.html

cc @jplevyak @PiotrSikora

**Comment by jplevyak** [comment]
I am working on this.

**Comment by yskopets** [comment]
Alternatively to Emscripten, [wasi-sdk](https://github.com/CraneStation/wasi-sdk) might be easier to integrate with.

**Comment by jplevyak** [comment]
Done by @lizan
