### ISSUE TITLE
Consider using typed values in WASM externalized functions

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy-wasm#11]
Current API is structured around using JSONs for passing data between WASM and the host.
This seems to be motivated by re-using RDS route metadata as the storage mechanism.

There are issues with this approach:
- structs are very inefficient on the wire
- structs cannot represent integers since JSON only supports doubles, the work around to use strings for integers is very costly

Given that WASM is integer oriented, the cost of transferring a single large integer across the module boundary is excessive in this design. Large integers get truncated in double representation.

Please consider using typed protobuf values instead of JSON as defined by https://github.com/googleapis/googleapis/blob/master/google/api/expr/v1alpha1/value.proto#L35

**Comment by PiotrSikora** [comment]
Hm? Which API are you talking about?

**Comment by kyessenov** [comment]
All the get/set metadata headers in WASM API.

**Comment by jplevyak** [comment]
The underlying data structures in envoy are Struct so that is what is exposed.  There is also a raw API if the underlying host system (i.e. not-envoy) has some other format.   You can use getMetadataValuePairs
and then load the raw bytes into whatever the underlying type is (e.g. uint64_t).  However and again, that depends on the underlying data format.  If they underlying format is say proto int64, then you would have to unmarshal the proto wire format.

**Comment by jplevyak** [comment]
We can provide additional helper functions in the high level API for common use cases.

Could you suggest some additional high level APIs that you have use cases for ?

**Comment by PiotrSikora** [comment]
IMHO, we shouldn't be simply exposing underlying data, because then we're going to lose ABI guarantees pretty fast... not to mention the portability of Proxy-WASM extensions across various proxies.

**Comment by kyessenov** [comment]
I've sketched an API in #42 . It seems a strict generalization of what we have, without the protobuf baggage. It should allow us to avoid putting stuff into protobuf for computed values, and avoid shipping the struct as a container between address space boundaries.

Regarding ABI: are you referring to WASI or some variant of? It is an interesting thought to structure API around UNIX file hierarchy.

How portable is existing API to other proxies? It appears full of Envoy-ism on the first sight (DynamicMetadata, HTTP/TCP filtering, callbacks, etc).

**Comment by kyessenov** [comment]
Some use cases:
- get peer pod labels:
 compare: `FindStruct("source", "labels")` vs `GetMetadata(Request)` and unmarshal `envoy.wasm.metadata_exchange.downstream`.
- get total byte count read so far:
 compare: `FindInt64("request", "size")` vs another method in ABI
