### ISSUE TITLE
Merge master branch into envoy-wasm

### ISSUE THREAD

**Issue by gargnupur** [envoyproxy/envoy-wasm#114]
*Title*: Merge master branch into envoy-wasm

*Description*:
Please merge master branch into envoy-wasm.
Kuat added ability to add upstream network filters in envoy master. (https://github.com/envoyproxy/envoy/commit/0f892c2385e7051d325d22b3f603cc60facedd6e) Need this for TCP Metadata work as Istio Proxy uses envoy wasm SHA.

**Comment by PiotrSikora** [comment]
Merged.
