### ISSUE TITLE
Migrate to wasm64 ABI

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy-wasm#125]
cc @jplevyak

**Comment by PiotrSikora** [comment]
Rust (and I imagine emscripten as well) are actually using `wasm32`, and if you pass complex types it will unpack them into i32s, (e.g. string is unpacked into `i32 pointer to data`, `i32 size`).

**Comment by jplevyak** [comment]
We are going to table this.  Wasm64 seems to be at least 2 years out and we would lose more precise typing of the ABI if we moved to using uint64_t for all functions at this time.
