### ISSUE TITLE
Cannot access node.id through WASM API

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy-wasm#13]
The API has no way to access node ID field.

**Comment by jplevyak** [comment]
I presume the cluster as well?  perhaps the locality and build version?

**Comment by kyessenov** [comment]
ID is needed since it has meaningful data in istio context. Istio does not use locality or build. Perhaps exposing the entire node object as a struct would fit the bill.

**Comment by PiotrSikora** [comment]
I believe this was fixed in #28.

Feel free to reopen if anything is still missing.
