### ISSUE TITLE
Uncaught WasmExceptions in WasmVm

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy-wasm#137]
Currently, stubs are throwing exceptions, which we don't catch in WasmVm, and which lead to Envoy exiting instead of VM being terminated and either restarted or replaced with a dummy filter rejecting all traffic.

cc @jplevyak

**Comment by PiotrSikora** [comment]
We need to fix this sooner rather than later.

**Comment by kyessenov** [comment]
To be fair, I'd rather take performat Wasm byte code than exceptions in Wasm.
The instruction set does not allow non-local jumps which are needed for `throw/catch`.
This is the same reason why goroutines destroy Wasm performance.

**Comment by PiotrSikora** [comment]
@kyessenov Those are not exceptions in Wasm code, but exceptions in the host and runtime (e.g. when Wasm code reaches `unreachable` Wasm instruction. Right now, any bugs in the code (which would normally result in `SIGSEGV`) are going to crash Envoy, even though Wasm is sandboxed, because we throw exceptions in Envoy for those cases.

**Comment by kyessenov** [comment]
Got it. Agree, failing Wasm filter should not crash envoy. We should also harden the interface on the host side, so that no ABI call can crash envoy in any state. Would be nice to do some fuzzing there.
