### ISSUE TITLE
Documentation for the WASM API Required.

### ISSUE THREAD

**Issue by jplevyak** [envoyproxy/envoy-wasm#16]
Documentation for the WASM API Required.

FAQ: onConfigure is only called if there is a non-empty configuration.

Please follow up with specific questions which should be addressed.

**Comment by yskopets** [comment]
I could work on this and create documentation similar to [WASI](https://github.com/WebAssembly/WASI/blob/master/phases/snapshot/docs/wasi_unstable_preview1.md).
