### ISSUE TITLE
Default vm_id to hash(content_of_wasm_module)

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy-wasm#167]
This will allow us to reuse unique instance per WASM module by default. Currently, we load all modules into "default" VM.

Add note that manually specified vm_id should include a version number, otherwise it won't be reloaded when new version of the module is loaded.

**Comment by jplevyak** [comment]
https://github.com/envoyproxy/envoy-wasm/pull/272

**Comment by PiotrSikora** [comment]
Fixed in #274.
