### ISSUE TITLE
WASM: Optimize http metadata exchange

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy-wasm#178]
In CPU measurements, enabling http metadata exchange server added about 10% total cpu in the standard tools/perf tests.

`dynamicMetadata.Set` is a very expensive operation since it call promo.merge underneath.

1. Move this to filterstate
2. If (1) is taking too long, add a cache in front of the "write" operation. It must be written to a place that has lifetime of the VM, and not that of the request.
3. On the return path, server side does not need to return metadata on every call. It can keep track of sources it has responded to and only respond if we have not responded before.
 We may need to add "epoch" as additional node identifier to ensure that restarts are handled correctly.

**Comment by mandarjog** [comment]
@kyessenov

**Comment by mandarjog** [comment]
https://snapshot.raintank.io/dashboard/snapshot/MOV74X8GrkMRKbMbDKgoQYjylXNFfQbb?refresh=10s&panelId=7&fullscreen&orgId=2

**Comment by bianpengyuan** [comment]
Potentially, for (2) we could use vm sharing mechanism, so that both filters will specify the same vm_id and different root context id. stats filter could get metadata exchange filter via its root context id. This way the cache is persistent VM's lifetime. But on the downside it couples stats filter and metadata exchange filter.

**Comment by kyessenov** [comment]
I'll work on using filter state of WASM filter to host all shared module state.

**Comment by kyessenov** [comment]
@jplevyak as an extra, I'll also clean up the use of stream info (no need to have 3 different ways to access the same object) and the metadata expression type.

**Comment by jplevyak** [comment]
obsolete, we moved to FilterState and we provide sharing of VMs.
