### ISSUE TITLE
v8 does not build on macos

### ISSUE THREAD

**Issue by bianpengyuan** [envoyproxy/envoy-wasm#18]
v8 cannot be built on mac due to a link error, which makes istio-proxy CI not green: https://github.com/istio/proxy/pull/2231.

I can get the same output as circleci on my mac locally:

```
ld: warning: could not create compact unwind for _forkedStackTrampoline: does not use RBP or RSP based frame
Undefined symbols for architecture x86_64:
  "wasm::vec<wasm::ExportType*>::free_data()", referenced from:
      wasm::vec<wasm::ExportType*>::~vec() in libv8_lib.lo(v8.o)
  "wasm::vec<wasm::ImportType*>::free_data()", referenced from:
      wasm::vec<wasm::ImportType*>::~vec() in libv8_lib.lo(v8.o)
  "wasm::vec<wasm::Extern*>::free_data()", referenced from:
      wasm::vec<wasm::Extern*>::~vec() in libv8_lib.lo(v8.o)
  "wasm::vec<wasm::ValType*>::free_data()", referenced from:
      wasm::vec<wasm::ValType*>::~vec() in libv8_lib.lo(v8.o)
  "wasm::vec<wasm::ValType*>::make_data()", referenced from:
      wasm::vec<wasm::ValType*>::vec(unsigned long) in libv8_lib.lo(v8.o)
  "wasm::vec<char>::free_data()", referenced from:
      wasm::vec<char>::~vec() in libv8_lib.lo(v8.o)
      wasm::vec<char>::reset() in libv8_lib.lo(v8.o)
  "wasm::vec<char>::make_data()", referenced from:
      wasm::vec<char>::vec(unsigned long) in libv8_lib.lo(v8.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

cc @PiotrSikora

**Comment by bianpengyuan** [comment]
Looks like the recipe only builds with x64 instead of ia32 (https://github.com/envoyproxy/envoy-wasm/blob/master/ci/build_container/build_recipes/v8.sh#L42). I will try to update the recipe to also supports mac.

**Comment by PiotrSikora** [comment]
@bianpengyuan but macOS is x86_64 nowadays.

Also, it definitely did built for macOS correctly at some point using this recipe, so something broke... I'll try to dig into this later today, but this might take a while due to build times :(

**Comment by PiotrSikora** [comment]
Ah, I just remembered... Last time I tried this on macOS was when I was still using V8 directly, without wasm-c-api, and the linking issue seems to be specific to wasm-c-api. Let me see if I can fix it.

**Comment by bianpengyuan** [comment]
Ok thanks! The reason I mentioned ia32 is that when searching `V8_ARCH`, all results suggests making that value ia32 when building on mac. Reason being `MacOSX has a 64bit kernel, but a 32 bit userspace`, though I am not sure whether this is related and could fix the issue.
