### ISSUE TITLE
Add name to wasm config API

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy-wasm#182]
1. Add WasmConfig.name --> This can be used in logs and config migration. For validation we should be able to associate a name with config proto and perform proto validation.
1a. It is more natural to identify a compiled in plugin by name.
2. Add bool required --> if extension fails to load reject config.

**Comment by PiotrSikora** [comment]
re 2 - in what scenario configuration with the extension that fails to load should be allowed?

**Comment by jplevyak** [comment]
I have added the name to the VMConfig.  Currently you will have to add it to your configuration if you want to have it in the VM.   Conversely I can have a call (e.g. getProperty("plugin_name") or somesuch) to get the value.

What do you think?

**Comment by mandarjog** [comment]
@PiotrSikora If I am adding a new telemetry filter, I would like to record the fact that there is error, but not reject the listener.  If a listener is rejected, *all* other changes that happen *after* this change will not be applied.

`required: false` lets you inject filters in a test mode.

**Comment by jplevyak** [comment]
Back to my question.  There is a "name" now in the configuration, however it isn't available to the WASM code unless the user passes it in the configuration.  

Do you want a call to get the "name" ?

Perhaps getProperty("plugin_name") ?

**Comment by mandarjog** [comment]
What do @jplevyak , @PiotrSikora @kyessenov think about adding a proto / struct in the configure() method. We potentially have several other fields that can be added there.
example: name, debug?, ready-only, shadow mode ...?

Otherwise `getProperty("plugin_name") ` is fine.

**Comment by jplevyak** [comment]
Done
