### ISSUE TITLE
Add support for remote datasources (RemoteAsyncDataProvider) for loading .wasm files from a URI.

### ISSUE THREAD

**Issue by jplevyak** [envoyproxy/envoy-wasm#187]
Add support for remote datasources (RemoteAsyncDataProvider) for loading .wasm files from a URI.

**Comment by PiotrSikora** [comment]
@yxue can you hook this all the way to Wasm loading of the code, and make sure that exceptions are handled correctly (e.g. when URI is not found, the configuration is rejected asynchronously).
