### ISSUE TITLE
Add cryptographic primitives to WASM API

### ISSUE THREAD

**Issue by robertpanzer** [envoyproxy/envoy-wasm#188]
*Title*: Add cryptographic primitives like SHA256 and RSA to the WASM API

*Description*:
This is a feature request.
It would be nice to have cryptographic functions like SHA256 and RSA (signature creation and validation) in the API.
Currently I can't find these in `proxy_wasm_api.h`.
Even though it would be perfectly possible to compile a C or C++ implementation of these algorithms to WebAssembly, many implementations like BoringSSL or nettle do this in assembly to utilize operations that are directly offered by the CPU. 
(See for example https://github.com/google/boringssl/blob/master/crypto/fipsmodule/sha/asm/sha256-586.pl)
Therefore it would be nice if such an implementation could be used directly from WASM.

For me in particular interesting would be functions to 
* import an RSA key so that it can be reused between multiple calls
* Compute a SHA256 hash
* Validate an RSA signature (with or without previous hashing)
* Generate an RSA signature (with or without previous hashing)

**Comment by jplevyak** [comment]
We are going to use the WASI crypto module going forward.   Assigned to @PiotrSikora for the spec part.  Assign back for the implemenation.
