### ISSUE TITLE
WASM context does not behave like an envoy filter

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy-wasm#20]
It turns out that the context object, which is the base for all modules, does not behave like an envoy filter. In particular, `onConfigure` and `onRequestHeaders` are invoked on two distinct instances of the context, meaning it's not clear how to pass configuration state to `onRequestHeaders`. This also explains problems with the struct cache I encountered earlier.

I think the expectation should be that the context should be associated with a request. That means its entire state machine should start at the request, go from configuration to action, and then die when the request finishes, just like a regular HTTP filter in envoy.

We should also be able to cache some pre-processed state between context instantiations. I think this needs another API to be able to coordinate state between instances of the context and instances of the config.

**Comment by jplevyak** [comment]
This is addressed by https://github.com/envoyproxy/envoy-wasm/pull/44 which differentiates and links the RootContext (onConfigure) and Context (onRequestHeaders).
