### ISSUE TITLE
Add secret access sandbox API (SDS)

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy-wasm#200]
Code running inside sandbox may need to access secrets thru the underlying SDS API.

Host API should support `fetchSecrets(std::string secret_name)` API based on the [SDS](https://github.com/envoyproxy/envoy/blob/master/api/envoy/service/discovery/v2/sds.proto#L27) protocol.

**Comment by incfly** [comment]
Can you give an example?

**Comment by kyessenov** [comment]
https://discuss.istio.io/t/v2-stackdriver-telemetry-and-workload-identity/6511/2 is an example.

**Comment by PiotrSikora** [comment]
> https://discuss.istio.io/t/v2-stackdriver-telemetry-and-workload-identity/6511/2 is an example.

That's quite different, IMHO.

Also, shouldn't the upstream cluster be configured with proper workload identity already? Wasm modules are not making those connections directly, but via Envoy using already configured upstream clusters.

**Comment by kyessenov** [comment]
SD uses Google gRPC client with a direct URI. Right now, it's using STS, and the feature is fetch a secret from SDS and reference it in GrpcService proto.
