### ISSUE TITLE
Unable to build a wasm filter with cmake and libprotobuf.bc

### ISSUE THREAD

**Issue by robertpanzer** [envoyproxy/envoy-wasm#207]
*Title*: libprotobuf.bc and libprotobuf.bc cannot be linked with em++

*Description*:
I am trying to build a wasm filter with cmake which compiles and links in 2 steps instead of using the example Makefile.base that does both in one step.
However em++ doesn't seem to be able to link libprotobuf.bc and fails with this error:
```
[100%] Linking CXX executable ../public/myfilter.js
/usr/local/Cellar/cmake/3.15.3/bin/cmake -E cmake_link_script CMakeFiles/myfilter.dir/link.txt --verbose=1
.../emsdk/fastcomp/emscripten/em++        -s WASM=1     -s BINARYEN_TRAP_MODE='clamp'     -O3 -g3     -s LEGALIZE_JS_FFI=0     -s EMIT_EMSCRIPTEN_METADATA=1     -DEMSCRIPTEN_PROTOBUF=1     .../envoy-wasm/api/wasm/cpp/libprotobuf.bc     --js-library .../envoy-wasm/api/wasm/cpp/proxy_wasm_intrinsics.js @CMakeFiles/myfilter.dir/objects1.rsp  -o ../public/myfilter.js
error: undefined symbol: _ZN40protobuf_google_2fprotobuf_2fany_2eproto14AddDescriptorsEv
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
error: undefined symbol: _ZN42protobuf_google_2fprotobuf_2fempty_2eproto14AddDescriptorsEv
error: undefined symbol: _ZN43protobuf_google_2fprotobuf_2fstruct_2eproto14AddDescriptorsEv
error: undefined symbol: _ZN45protobuf_google_2fprotobuf_2fduration_2eproto14AddDescriptorsEv
error: undefined symbol: _ZN6google8protobuf14DescriptorPool24InternalAddGeneratedFileEPKvi
```

I only found [this question on StackOverflow](https://stackoverflow.com/questions/55252435/emscripten-library-make-from-cmake-cannot-link/55255096) that indicates that the format of libprotobuf.bc could be a problem. And indeed it starts with `!<arch>` instead of `BC` while the compiled object files all start with `BC`:
```
hexdump -C myfilter.cc.o|head
00000000  42 43 c0 de 35 14 00 00  05 00 00 00 62 0c 30 24  |BC..5.......b.0$|
...
hexdump -C libprotobuf.bc|head
00000000  21 3c 61 72 63 68 3e 0a  2f 20 20 20 20 20 20 20  |!<arch>./       |
```

*Repro steps*:
Create a project with CMake that links libprotobuf.bc and try to build it.

**Comment by PiotrSikora** [comment]
cc @jplevyak

**Comment by PiotrSikora** [comment]
@robertpanzer did you try using `Makefile.base_lite` and `-DEMSCRIPTEN_PROTOBUF_LITE=1` instead of full protobuf?

Also, what's the version of `protoc` that you have installed in the system (`protoc --version`)? It has to match version used to generated `.bc` files, i.e. `v3.6.1` (or `v3.9.1` with recent `master`, i.e. with #215 merged).

**Comment by robertpanzer** [comment]
Thanks, it works now with the latest master!
I had 3.6.1 before and the symbols that the linker complained about definitely showed up in `nm libprotobuf.bc`. Playing with wrong protoc versions rather seems to result in compile errors, at least when mixing 3.6.1 and 3.9.1.

Indeed it seems like libprotobuf.bc now has the format that was differing from the other object files:
```
hexdump -C libprotobuf.bc
00000000  42 43 c0 de 35 14 00 00  05 00 00 00 62 0c 30 24  |BC..5.......b.0$|
...
```

I have no idea if this is just a coincidence or if this is related.

Is there any information how the .bc files are created?
It would be great to have some details on how this is created. Is it just going to `protobuf/cmake/build` and run `emconfigure cmake .. && make`?

**Comment by PiotrSikora** [comment]
Yes, see: https://github.com/envoyproxy/envoy-wasm/blob/2e56dfd99d2fc572a770b765efd2872b58cb6e4e/api/wasm/cpp/README.md#rebulding-the-protobufbc-files

It's possible that the `.bc` file for v3.6.1 was generated differently, but it shouldn't. cc @jplevyak

**Comment by robertpanzer** [comment]
Is it possible that libprotobuf.bc from 3.6.1 was built with emscripten 1.38.25 (afair the previous recommended version) and the one from 3.9.1 was built with 1.38.42?
So could it be due to a fix in emscripten?
