### ISSUE TITLE
Export ABI version used to build .wasm module in global variable

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy-wasm#214]
Export ABI version used to build .wasm module in global variable.

**Comment by PiotrSikora** [comment]
@jplevyak any idea on how to do it in Emscripten? I couldn't find any way to export a global value.

**Comment by yskopets** [comment]
Alternatively, a custom section in WASM file could be used for this kind of information.

E.g., Rust has a [very simple API](https://rustwasm.github.io/book/reference/js-ffi.html#custom-sections) for doing this.
