### ISSUE TITLE
Investigate/Mitigate memory usage for stats.

### ISSUE THREAD

**Issue by jplevyak** [envoyproxy/envoy-wasm#219]
There is concern that memory usage will be high and that the memory will not be reclaimed.  It seems that StatnameSet does dedup and get GC'd but StatNamePool does not dedup and does not get reclaimed.

**Comment by jmarantz** [comment]
I think a more serious issue is mutex contention, whenever a string is concerted into a stat.

As long as common wasm pattern is to capture counter/gauge/histogram handles on startup it should be OK, but if anything is looked up by name during request processing there is a going to be a thead contention issue.
