### ISSUE TITLE
Callbacks should never pass data in the arguments.

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy-wasm#223]
Wasm modules should call helper functions and request data as needed.

**Comment by mandarjog** [comment]
@PiotrSikora can you elaborate on why?  Is it just for buffer management ?

**Comment by PiotrSikora** [comment]
We pass memory ownership from host to Wasm module when passing data in arguments, but when Wasm module isn't interested in it and ignores it (instead of freeing), then the memory is never freed.

**Comment by mandarjog** [comment]
Does this apply to `onData` type calls?

**Comment by PiotrSikora** [comment]
Fixed in #274.
