### ISSUE TITLE
Provide protobuf-less SDK builds

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy-wasm#226]
protobuf is only needed for gRPC, so it shouldn't be a hard dependency.

**Comment by yskopets** [comment]
As far as I understand, Protobuf is also used in responses from `proxy_get_property`

**Comment by kyessenov** [comment]
If we don't use protobuf, what's the serlialization format we should be using?

**Comment by yskopets** [comment]
I think, Protobuf makes perfect sense for production use cases.

Non-production uses cases include quick prototyping and debugging/troubleshooting. This is where you, most likely, just want to dump into the log all available internal state of Envoy. And JSON becomes more convenient.

**Comment by jplevyak** [comment]
fixed.
