### ISSUE TITLE
Potential memory leak in proxy_getMetadata

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy-wasm#228]
There is a potential memory leak while accessing metadata is 1.3.
Caller does not free it because the API does not require it,
something else needs to

```getRequestDestinationPort(int * ) --> proxy_getMetadata()  --> copyToPointerSize --> alloc```

If I passed in the address of a stack variable to getRequestDestinationPort
someone else needs to free it. may be proxy_getMetadata() ?

**Comment by kyessenov** [comment]
This code is gone in master of envoy-wasm. It's using the generic getProperty. Does it have the same problem?

**Comment by mandarjog** [comment]
I will check, but we can do code inspection first. Is the latest istio/proxyv2 using the tip of envoy?

**Comment by kyessenov** [comment]
I think so.

**Comment by kyessenov** [comment]
I think this can be closed since the ABI changed and these methods are no longer present.

**Comment by mandarjog** [comment]
We may need to fix this in 1.3
