### ISSUE TITLE
Context plugin should not shared by all filters

### ISSUE THREAD

**Issue by bianpengyuan** [envoyproxy/envoy-wasm#249]
IIUC With https://github.com/envoyproxy/envoy-wasm/pull/208, the same filter (without vm_id) on all listeners will be running in one VM per thread and share the same Root context. Root context holds a plugin data structure which includes per listener information such as metadata, direction. This is wrong since now filters on different listeners will be configured with the same root context / plugin, which are initiated with the first listener. This causes filters to malfunction: https://github.com/istio/istio/issues/17811. I don't see an easy fix, it needs some surgery on the code.. This is not captured by istio/proxy test because it runs only one listener/filter per envoy instance.

@jplevyak @PiotrSikora @mandarjog

**Comment by bianpengyuan** [comment]
Also if I follow the code correctly, the original code will clone a new VM per filter per listener:
https://github.com/jplevyak/envoy-wasm/blob/3530007a221ecea543f500d7258f36f0f070b1c1/source/extensions/filters/http/wasm/wasm_filter.cc#L32

After the change, the same filter of all listeners will share the same VM:
https://github.com/jplevyak/envoy-wasm/blob/1593c03255f2f9d0583a11cf0fa9fa8bebf8fd32/source/extensions/filters/http/wasm/wasm_filter.cc#L33

Is this intended? This indeed saves some overhead, but the same filter might behave differently for different listeners, like stats filter initiated differently for outbound / inbound listener.

**Comment by mandarjog** [comment]
@jplevyak @PiotrSikora it seems that the assumption is that if two filters `onConfigure` takes the same set of arguments, they are the *same* filters. This assumption is incorrect because filters make use of ambient information, like `traffic direction` in case of the mx and stats filters.

I expect setting vm_ids to solve this problem. The other approach is for the filter to declare what it needs.

**Comment by jplevyak** [comment]
https://github.com/envoyproxy/envoy-wasm/pull/274

**Comment by jplevyak** [comment]
The plugin is now dynamically switched on listener specific calls (on_configure, on_start) for the RootContext. On calls which are not plugin specific (on_grpc_XXX) the plugin is not available and requests for listener specific information will return NotFound.
