### ISSUE TITLE
Shared root context causes a race

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy-wasm#256]
Sharing a root context between vm_id ID1 and vm_id ID2 causes a race, whereas ID2 acquires the config of ID1.
This is observed (non-deterministically) for null VM here: 
https://github.com/istio/proxy/blob/master/test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go#L78

/cc @PiotrSikora @jplevyak @mandarjog

**Comment by bianpengyuan** [comment]
Here is generated envoy configs that causes race: https://gist.githubusercontent.com/bianpengyuan/ad97581bac2b769f34b8b9fec5aa2ffa/raw/17bd98780132eeb03893d84fdd00490409cda481/wasm.yaml

**Comment by kyessenov** [comment]
The race was identified to be:
1. registration call from the plugin to Opencensus singleton, last config won
2. gRPC calls from the plugin to the testing endpoint - first RPC won

This is a logic problem in the plugin after all.
