### ISSUE TITLE
Zombie listeners gradually slow down envoy

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy-wasm#290]
Running with null vm, it appears that listeners are never cleaned up. Combined with ticks, the cumulative effect is significant as data path takes more than 5s to process.
See https://github.com/istio/proxy/pull/2507 for reproduction.

**Comment by kyessenov** [comment]
@jplevyak @PiotrSikora @mandarjog 
The effect is visible within 10s on ASAN/TSAN, 90s on optimized build.

**Comment by PiotrSikora** [comment]
Could you verify if that's still the case with V8 or is that unique to NullVM?

**Comment by kyessenov** [comment]
We don't test V8 in istio/proxy so hold on while I figure out the baseline.

**Comment by kyessenov** [comment]
This is due to drain-time-s set to 45s. We need to be careful not to put too many WASM resources into draining listeners.
