### ISSUE TITLE
Share filterstate between upstream and downstream filters

### ISSUE THREAD

**Issue by gargnupur** [envoyproxy/envoy-wasm#291]
*Title*: Share filterstate between upstream and downstream filters

*Description*:
Currently, upstream filters and downstream filters have their own connection objects because of which they can't share filterstate between each other. This hampers flow of metadata between filters. In our case specifically between upstream metadata_exchange filter and downstream stats filter.

[optional *Relevant Links*:]
I tried making a change in envoy to support this by sharing filterstate between upstream and downstream filters as follows: https://github.com/envoyproxy/envoy-wasm/compare/master...gargnupur:nup_upstream_filterstate?expand=1
But I see that in upstream filter, upstreamFilterstate is not null but when downstream filter, access it, the values set by upstream filter are not there. Is the above approach right way to do this?

**Comment by gargnupur** [comment]
Found a better solution for this : PR in review: https://github.com/envoyproxy/envoy/pull/9190

**Comment by jplevyak** [comment]
Fixed AFAICT
