### ISSUE TITLE
Provide an accessor for root/route context from the request context

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy-wasm#30]
There is no simple way to access route-level context from request-level context.
Consider two RDS routes, with two different configs (e.g. inbound and outbound):

- route_config 1 with null VM plugin with config X
- route_config 2 with null VM plugin with config Y

During request processing, we receive a call back onRequestHeaders but it is not clear how to associate it with either of the route plugin configs.

**Comment by jplevyak** [comment]
Could you clarify what specific data you want?  We have access to the request route metadata.  Is there another bit of data we need and if so could you provide a pointer into the envoy codebase?

**Comment by kyessenov** [comment]
I think this is mostly for the config. Basically, for every request in Envoy you have the following objects:
- filter factory that holds the config
- filter instance that gets the callbacks
In Envoy, you can pass the config from the factory to the instance. I think we want something similar in WASM. The root context pointer might be right solution to this.

**Comment by jplevyak** [comment]
https://github.com/envoyproxy/envoy-wasm/pull/44
