### ISSUE TITLE
C++ SDK passes back to Envoy pointers to local variables on WebAssembly execution stack instead of pointers to WebAssembly Linear Memory

### ISSUE THREAD

**Issue by yskopets** [envoyproxy/envoy-wasm#329]
*Title*: *C++ SDK passes back to Envoy pointers to local variables on WebAssembly execution stack instead of pointers to WebAssembly Linear Memory*

*Description*:

Here is a fragment of C++ SDK (api/wasm/cpp/proxy_wasm_api.h):
```
inline WasmDataPtr getHeaderMapValue(HeaderMapType type, StringView key) {
  const char* value_ptr = nullptr;
  size_t value_size = 0;
  proxy_get_header_map_value(type, key.data(), key.size(), &value_ptr, &value_size);
  return std::make_unique<WasmData>(value_ptr, value_size);
}
```

* Notice function call `proxy_get_header_map_value(type, key.data(), key.size(), &value_ptr, &value_size);` where pointers to local variables on WebAssembly execution stack get passed back to `Envoy`
* `Envoy` assumes that these are the pointers to `WebAssembly Linear Memory` and calls  `wasm_vm_->setWord(size_ptr, Word(size))` to modify `WebAssembly Linear Memory` at those locations

*Expected behaviour*:
* According to [WebAssembly Specification](https://github.com/WebAssembly/design/blob/master/Semantics.md#linear-memory), `Linear memory is sandboxed; it does not alias other linear memories, the execution engine's internal data structures, the execution stack, local variables, or other process memory.`
* Therefore, it's not valid to pass pointers to local variables on WebAssembly execution stack instead of pointers to `WebAssembly Linear Memory`

**Comment by jplevyak** [comment]
This is not an issue.  The WebAssembly specification implemented by Emscripten using a shadow stack in linear memory for when a pointer is taken to a value which would otherwise be on the execution engine's execution stack.

If that was not the case the existing implementation would not work since we index into linear memory in order to write those variables ergo they must be in linear memory.
