### ISSUE TITLE
Wasm TEST: generate a test filter

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy-wasm#333]
Generate a test filter(s) that gets every callback, and in every call back it should call every host function. Some functions do not make sense, like `set_headers` in a log call back. However nothing should crash envoy.

We need to decide what is the correct way of failing a host function that is not allowed in a certain  call phase.

**Comment by mandarjog** [comment]
@PiotrSikora @jplevyak

**Comment by jplevyak** [comment]
FYI: As part of upstreaming we are building full coverage for with V8 and the null VM.
