### ISSUE TITLE
Provide basic metadata and versioning scheme for modules

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy-wasm#34]
Define basic properties of a module to make it future-proof:
- sandbox version that it supports
- WASM VM capabilities
- signature from the producer
- anything else?

Provide a mechanism to attach this manifest to a module.

/cc @douglas-reid (who might be interested in WASM distribution infrastructure)

**Comment by douglas-reid** [comment]
I'm very interested in this topic.

I think your original list missed a few basics that may be base assumptions:

- unique name 
- tag(s)
- date of publish

And probably some way of adding metadata generically (allow publishers to describe inclided lib versions or other attributes important at audit time, etc.).
