### ISSUE TITLE
filter fetched from a remote source crashes on reading config

### ISSUE THREAD

**Issue by yuval-k** [envoyproxy/envoy-wasm#352]
there's currently a lifetime issue when reading config data if the filter is initialized form a remote location. 
I fixed it in here:
https://github.com/yuval-k/envoy-wasm/commit/541b2c1155fffb15ccde92b8324f3e38f7339ba6

essentially the lifetime of the config variable is as the FilterConfig ctor, and need to be copied if the callback is not called inline - which is the case when the filter is loaded from a remote location.

I can open a PR, but wasn't sure if I should do it here, or wait for this filter to be unstreamed.

**Comment by yuval-k** [comment]
cc @jplevyak

**Comment by jplevyak** [comment]
fixerd thanx.
