### ISSUE TITLE
Add api definition for closing Context connection

### ISSUE THREAD

**Issue by pawalt** [envoyproxy/envoy-wasm#354]
It'd be useful to be able to close a connection in the WASM filter so you could do real network filtering. Ex. close a connection if the WASM filter sees a packet w/ some body that it doesn't like. I've tried to implement this myself; unfortunately, `getConnection` returns a const while `Connection::close` is non-const, so it can't be called.
If someone could point me in the right direction on this, that would be great.

**Comment by Erezf-p** [comment]
@pawalt  Is there any progress on that?

**Comment by pawalt** [comment]
I never was able to get past this point. If someone else wants this, they'll have to implement it it seems.
