### ISSUE TITLE
How will data in WASM Filters work?

### ISSUE THREAD

**Issue by gxb5443** [envoyproxy/envoy-wasm#367]
*Title*: How will data work in WASM Filters?

*Description*:
Is there any idea as to how WASM files will access dynamic data? Like if I build a filter which uses a special route table, or a list of IP addresses or users or something, what will be the best way to get that data into the filter? Obviously network requests are a no go, but will WASM have access to the file system? Or in those scenarios would whatever data the filter needs have to be compiled into the WASM distributable?

**Comment by nilslice** [comment]
@gxb5443 - while not a full answer to your question, take a look at this section of the architecture doc in progress: https://docs.google.com/document/d/1YPbxuEIPwKsW4Ft73diHRBTUNbYIlrQHNnS9dXdn778/edit#heading=h.auav01sm13r2

**Comment by gxb5443** [comment]
@nilslice Hey thanks for the info. This seems like it's on the right track of what I'm looking for. Do you have any idea how long that dynamic data, e.g. the "shared queue" discussed in the log consolidator example of that doc would live? And is there any doc or even support for making such a singleton in envoy now?

**Comment by jplevyak** [comment]
Shared data lives indefinitely.  The Shared queue lives only as long as it takes to deliver the cross-thread message containing the data to the other VM.  You can make a singleton right now by adding a wasm service configuration to the bootstrap envoy configuration (see api/envoy/extensions/wasm/v3/wasm.proto in the envoy-wasm repo).
