### ISSUE TITLE
WAVM build shouldn't hardcode clang version

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy-wasm#37]
Latest envoy builds with clang-8, while WAVM build script is hard coding `clang-7` for CC/CXX. 

https://github.com/envoyproxy/envoy-wasm/blob/master/ci/build_container/build_recipes/wavm.sh#L14

**Comment by PiotrSikora** [comment]
Yeah, I have some fixes locally to let WASM run on CI and CentOS, and it's already fixed there.

I'll try to send some of them later today, but it takes forever to test those changes...

**Comment by PiotrSikora** [comment]
Fixed in #49.
