### ISSUE TITLE
Add apis for adding tags to span from wasm filters

### ISSUE THREAD

**Issue by mohit-a21** [envoyproxy/envoy-wasm#383]
I am working on some envoy wasm filters where I want to add tags to span from the wasm filters. I didn't come across any API which allows me to modify active spans from the filter context. 

I would like to add the following API:

```
WasmResult activeSpanSetTag(StringView key, StringView value);
```

The APIs would be implemented similar to the header modification APIs defined as of now: https://github.com/envoyproxy/envoy-wasm/blob/49f411875801c85fc25b869da77ef98cde3f7f65/api/wasm/cpp/proxy_wasm_api.h#L629

I would be able to add a patch for this if accepted.

**Comment by jplevyak** [comment]
@PiotrSikora could you triage to determine if we want this as a full ABI, envoy specific ABI or foreign function?

**Comment by mohit-a21** [comment]
@jplevyak, @PiotrSikora Now that the envoy specific ABI support is available, do you guys think we can add this as an envoy specific ABI?
