### ISSUE TITLE
Reconsider using protobuffers for Wasm state

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy-wasm#389]
Current shared state API looks like this:
```c++
// write
setFilterState(string key, string data_buffer)
// read
google::protobuf::Struct data;
getMessageValue({"filter_state", key}, &data);
```

The `data_buffer` is stored in Envoy as a raw data buffer without trying to parse it as a protobuf.

There are issues with this API:
1. Each read and write costs a protobuf serialization. Protobuf is CPU heavy, and demands client libraries.
2. Values are blobs. We cannot read partial state, e.g. a field of `data`.
3. Inter-operation with native envoy facilities is complicated. Since envoy is not aware of the internal structure of the blob, we can't make native extensions consume the stored blobs (e.g. access log or CEL runtime).

The proposal is, in short, to get rid of the protobuf here. That means the revised API would only be storing primitive values (ints, strings, bools, string maps perhaps, since they are needed in istio), and would compensate for the lack of structure by using a nested key scheme. For example, the above would be changed to:
```c++
// write
setStringValue({"key", "field1"}, data.field1);
setIntValue({"key", "field2"}, data.field2);
// read
string field1;
getStringValue({"filter_state", key, "field1"}, &field1);
```

cc @jplevyak @PiotrSikora

**Comment by jplevyak** [comment]
Fixed
