### ISSUE TITLE
Enable looking through connection filter state for Http for network mxc filter

### ISSUE THREAD

**Issue by gargnupur** [envoyproxy/envoy-wasm#402]
*Title*: Enable looking through connection filter state for Http

*Description*:
PR: https://github.com/envoyproxy/envoy-wasm/pull/394 removed fallback of looking through connection filter state but it's needed in case of http for network metadata exchange filter

**Comment by jplevyak** [comment]
Is this still required @gargnupur  ?

**Comment by gargnupur** [comment]
@jplevyak : this will be required, if we decide to use our mechanism for ALPN based metadata exchange for TCP for HTTP too.
@mandarjog , @kyessenov : what do you guys think?

**Comment by kyessenov** [comment]
Yeah, I think this is needed. There were some changes in envoy once I added TCP logging connection-level filter state. It might just work now, or if not, we should make it work.
