### ISSUE TITLE
gRPC CreateInitialMetadata callback not work

### ISSUE THREAD

**Issue by bianpengyuan** [envoyproxy/envoy-wasm#414]
onCreateInitialMetadata is triggered inline in SendRaw, at that time grpc call token is not yet returned into module, which makes onCreateInitialMetadata always fail. This is the tentative fix in istio envoy repo: https://github.com/istio/envoy/pull/152/files#diff-3367fe470b910c37aac0a6fd5856a936 not sure if it is the proper fix. If yes I could patch the same fix in envoy-wasm repo.

**Comment by PiotrSikora** [comment]
Looking at this now, I'm wondering if there is any reason to have this callback at all? It seems that we're mimicking Envoy's APIs here, but `proxy_grpc_call` could be simply include initial metadata as one of the input parameters, right? or am I missing some use case?

**Comment by kyessenov** [comment]
+1. Metadata should just be part of the call.

**Comment by bianpengyuan** [comment]
How do you express other operation other than adding if initial metadata becomes a param?

**Comment by PiotrSikora** [comment]
> How do you express other operation other than adding if initial metadata becomes a param?

Do you have a real use case for that?

**Comment by bianpengyuan** [comment]
No I don't. This is the first time I tried out this callback :) . I am fine with eliminating it from the ABI and turn it into a param. Will update the PR to do that.

**Comment by kyessenov** [comment]
No ABI change in 1.4 please. Ideally, 1.5 either. The ABI cleanup needs to happen after the release.

**Comment by bianpengyuan** [comment]
No more change to 1.4 for sure. My current priority is to get something working for release-1.5, no matter it involves an ABI change or not.

@PiotrSikora Would it be acceptable if we just do the minimal fix in release-1.5 and master like release-1.4 (https://github.com/istio/envoy/commit/37dbbd43ed8020c4066e0737d1fc7902fceef36a#diff-3367fe470b910c37aac0a6fd5856a936), which involves no abi change. I will also add a test for it. Later on we can clean up the ABI after release-1.5 is out.

**Comment by PiotrSikora** [comment]
I'm fine with having the minimal fix in `release-1.4` and `release-1.5`, but I'd rather do a proper fix in `master`.

**Comment by bianpengyuan** [comment]
Ok then I will do a cherry-pick of release-1.4 change to release-1.5 with a test. Then update master later to eliminate the callback.

**Comment by jplevyak** [comment]
Fixed
