### ISSUE TITLE
Decide the future of wasm stress test

### ISSUE THREAD

**Issue by gargnupur** [envoyproxy/envoy-wasm#419]
Wasm stress test at times fail when merging from base envoy.

Skipping some tests for now and using this bug to decide their future

**Comment by gargnupur** [comment]
@PiotrSikora , @duderino : I don't think we need this bug anymore, close it?

**Comment by PiotrSikora** [comment]
@jplevyak we ripped out stress test while you were away, because it was making import extremely painful, and it doesn't look that it would be accepted upstream anyway. Do you want to revisit that change or should we close this?
