### ISSUE TITLE
Evaluate performance of a simple expression

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy-wasm#43]
We have several ways to run side-effect free code:
- native Envoy filter
- Envoy WASM module
- Envoy WASM C++ native filter

We should evaluate these different ways to run the code to isolate CPU/memory characteristics.
Additionally, for interpreted symbolic expressions, we have:
- interpreter in WASM
- interpreter in C++
- generated WASM instructions

To enable this work, we need standard interfaces for Envoy across implementations to limit the environmental factors.

**Comment by jplevyak** [comment]
Obsolete, we now include CEL evaluated in C++ available from Wasm.
