### ISSUE TITLE
Make the HTTP headers accessible in the HTTP body callback for WASM

### ISSUE THREAD

**Issue by gbrail** [envoyproxy/envoy-wasm#445]
Now that we can very soon write a filter that accesses and modifies the HTTP request and response bodies, it will also be important to access and modify the HTTP headers in the body callback.

For example, consider that we want to read the entire response body, transform it to another format, and return the result. We'd need to:

1) Return StopIteration from the response header callback
2) Return StopIterationAndBuffer from the response body callback until we have the whole body
3) Read the response body and replace the buffered body with the result
4) Update the content-length and content-type headers as well as others

As another example, perhaps we want to read the body and set some header that represents a hash or checksum.

The Envoy C++ filter interface doesn't pass a reference to the HeaderMap to the body callbacks but it's still there. It'd be very useful to make it available in the body callbacks rather than zeroing out as we do today,

**Comment by PiotrSikora** [comment]
Aren't 1 and 2 mutually exclusive?

Also, in general, for cases like the one you described, filters usually just remove `Content-Length` header (since it's effectively optional with HTTP/1.1 chunked encoding, HTTP/2 and HTTP/3), and proactively change the `Content-Type`, since it's not payload-dependent.

Having said that, I agree that we could keep headers around for longer, though, we can always just cache them in the SDKs.

**Comment by gbrail** [comment]
I'll suggest a few additional cases:

1) We want to write a filter that reads the request body and adds a header containing a hash or a checksum.
2) We want to write a filter that reads the response body and, depending on the content, converts the response into an error. (For instance, the upstream server returned invalid data or returned data that contains confidential information.)
3) We want to let people manipulate requests and responses using some sort of a scripting language and it's more complicated for the user of the language to have to remember what things can be changed in what order, like remembering to change all the headers before looking at the body.

I would love to see this implemented by simply leaving the pointer to the headers set to the headers returned to the "encode/decodeHeaders" callback if the header callback in WASM returned "StopIteration."
