### ISSUE TITLE
Add clear_route_cache() to anything which could affect the route since it is not in the proxy-wasm ABI anymore.

### ISSUE THREAD

**Issue by jplevyak** [envoyproxy/envoy-wasm#450]

**Comment by mandarjog** [comment]
Sometimes you don’t want automatic route recalculation. 
If a filter sanitized headers or processes them and puts them in filterstate we may not want route recomputed.

**Comment by PiotrSikora** [comment]
@mandarjog I originally agreed with @jplevyak, but I think you're right. Always reevaluating the route on `set_map(HttpRequestHeaders, ...)` would break simple rewriting headers for upstream.
