### ISSUE TITLE
Stats purge: stats accumulate indefinitely 

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy-wasm#451]
envoy impl of proxy wasm uses one stats Scope. The result Is that stats accumulate indefinitely even if they are no longer being updated. 

In mixer there was a periodic purge of stats which would ensure that zombie stats do not stick around.

We either want an api or if that’s not possible then automatic behavior that purges stats if requested.

One option is to create a sub scope for a filter and then only purge that.

**Comment by mandarjog** [comment]
@jplevyak @douglas-reid

**Comment by kyessenov** [comment]
How serious is this leak? I imagine it's probably worst at the hub in the hub-and-spoke pattern?

**Comment by mandarjog** [comment]
Yes at ingress in a large system like serverless/knative.

**Comment by jplevyak** [comment]
Maybe we can rope @jmarantz in on this one.  According to the estimates we made in meetings the amount memory used should be small.  We use a single Scope and a single StatNameSet which is managed via a shared_ptr in each Wasm object.   When you define a metric, it creates the Stat returns a token to the VM.  We would have to purge those tokens from the VM and from the Wasm object.  Once that was done, in theory, the Stat should be garbage collected, but we will need to talk to @jmarantz to be sure.

We could add a releaseMetric() call which would purge the entry from the Wasm object and you could use in the plugin code.

**Comment by jplevyak** [comment]
Please see the discussion on #452 @mandarjog 
We could enable purging of all stats on a VM basis by recreating the Scope object.   You would then need to defineMetric() again for all metrics you want to use.  Is this something you would be interested in?

**Comment by jmarantz** [comment]
Actually the Counter& returned in this scenario would be the same. ie I believe this test will work:
```
  ScopePtr s1 = stats_store_.createScope("scope");
  ScopePtr s2 = stats_store_.createScope("scope"); // second scope has same name
  EXPECT_NE(s1.get(), s2.get()); // two different scope objects.
  StatNameManagedStore storage("foo", stats_store_.symbolTable());
  Counter& c1 = s1->counterFromStatName(storage.statName());
  Counter& c2 = s2->counterFromStatName(storage.statName());
  EXPECT_EQ(&c1, &c2); // Ultimate the stats are name-matched in the allocator, and they'll both be called "scope.foo".
```

So I think you can share the maps populated from defineMetric.

**Comment by mandarjog** [comment]
@jplevyak we will have to make adjustments to code to call define metrics again, and we will need api support.
The naive way of calling defineMetric if incrementMetric fails will not work as we may get false hits.

1. If we somehow know when to purge the internal cache that would do it.
2. If we can eliminate the need for cache, they would work too.
