### ISSUE TITLE
Streaminfo not accessible in async callback

### ISSUE THREAD

**Issue by bianpengyuan** [envoyproxy/envoy-wasm#458]
When making async call inside `onRequestHeader` (and I think the other event handlers as well), pointers to streaminfo's data struct (e.g. request headers) will be reset after return from `onRequestHeader`, which makes those data structure not accessible in async call's callback. Seems like `SetEffectiveContext` does not have access to those data. We probably should keep those pointers if module event handlers return StopIteration.

**Comment by jplevyak** [comment]
What other aspects other than the headers do you need ?

**Comment by bianpengyuan** [comment]
I only need headers for the sample plugin. I think your PR already covers all other aspects that I can think of.
