### ISSUE TITLE
WASM CPP SDK: Access connection information

### ISSUE THREAD

**Issue by stoader** [envoyproxy/envoy-wasm#474]
I'm trying to access connection related information such as client certificate in case of TLS connection from inside a WASM network filter using the [WASM CPP SDK](https://github.com/envoyproxy/envoy-wasm/tree/master/api/wasm/cpp). The [Context::onNewConnection]( https://github.com/envoyproxy/envoy-wasm/blob/master/api/wasm/cpp/proxy_wasm_api.h#L373) is invoked on the filter implementation when a new connection is established, however I can't seem to find any APIs in the WASM SDK to access information that pertains to the established connection.

Is there any support for that in the SDK? If so can you point me to any examples or documentation that I could look at ? 

Any help is greatly appreciated.

**Comment by kyessenov** [comment]
You can use `getValue` calls to read the context properties. Some are documented here https://github.com/istio/istio/wiki/Configurable-V2-Metrics#expressions-used-for-values

**Comment by stoader** [comment]
Do you know off the top of your head the name of the context property that refers to the opened network connection object? Or where can I find that in the source code?

**Comment by kyessenov** [comment]
You can't access objects directly from Wasm. You can only read primitive
values or serialized bytes.

**Comment by stoader** [comment]
So if I understand it correctly I should be able to get the `Subject`  of the client certificate of a downstream mTLS connection by simply querying the right context property  using `getValue`. Is this property list https://github.com/envoyproxy/envoy-wasm/blob/master/source/extensions/filters/common/expr/context.h#L48 what I should look into   ? (e.g. `getValue("connection.mtls", ..); getValue("connection.subject_peer_certificate", ..);` and so on)

**Comment by kyessenov** [comment]
Yeah, some working examples are here: https://github.com/istio/proxy/blob/master/extensions/common/context.cc#L153

**Comment by stoader** [comment]
Thanks @kyessenov , this helped to move forward.

There are several WASM CPP SDKs out there. Which is the recommended one to build our Wasm filters based on:

1. [envoyproxy/envoy-wasm](https://github.com/envoyproxy/envoy-wasm/tree/master/api/wasm/cpp)
1. [proxy-wasm/proxy-wasm-cpp-sdk](https://github.com/proxy-wasm/proxy-wasm-cpp-sdk)

?

**Comment by kyessenov** [comment]
It's in transition from 1. to 2. I don't know if 2. is fully wired right now.
