### ISSUE TITLE
Eliminate protobuf from ABI

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy-wasm#485]
getProperty can return a protobuf struct sometimes (e.g. "node.metadata").
We should remove that encoding and use the same "headermap" style encoding instead.

**Comment by jplevyak** [comment]
I don't think it is part of the ABI anymore... assigning to @PiotrSikora for triage.

**Comment by jplevyak** [comment]
Fixed.  There are now targets in the SDK for protobuf free SDK.

**Comment by kyessenov** [comment]
I don't think this is fully sovled. ABI is not usable without protobuf in some cases, e.g. trying to read node metadata. I think we need to use a different encoding for structured data, something like header pairs.

**Comment by jplevyak** [comment]
That is not part of the ABI.  That is an Envoy specific subset of the SDK
and the SDK now has fully optional support for protobufs.  Of course Envoy
Node metadata is in protobufs, but that is not in the ABI.

If you want to add a feature request: convert Envoy protobufs on the host
side into X (where X is flatbuffers, key-value pairs or whatever) make a
proposal.  Perhaps CEL can do this for us.

**Comment by kyessenov** [comment]
Sure, I am suggesting to convert protobuf to key-value pairs or something simple like that. I'd like to avoid protobuf bytes between host and guest to truly remove protobuf as a dependency.
