### ISSUE TITLE
Can't access getConfiguration() from onConfigure()

### ISSUE THREAD

**Issue by gxb5443** [envoyproxy/envoy-wasm#501]
**WARNING: If you want to report crashes, leaking of sensitive information,
and/or other security issues, please consider
[reporting them using appropriate channels](https://github.com/envoyproxy/envoy#reporting-security-vulnerabilities).**

**Issue Template**

*Title*: *Can't access getConfiguration() from onConfigure() *

*Description*:
When using the latest version of envoy-wasm envoy binary, my filter (compiled against the same version of envoy-wasm) crashes envoy with the message `Failed to load WASM module due to a missing import: env.proxy_get_configuration`.  I access the function in the onConfigure like `auto conf = getConfiguration();`. When I remove that line the error goes away.

**Comment by jplevyak** [comment]
That function has been removed.  There are now buffer types: VmConfiguration and PluginConfiguration.
