### ISSUE TITLE
Failed to load WASM module due to a missing import: env.proxy_set_buffer_bytes

### ISSUE THREAD

**Issue by Erezf-p** [envoyproxy/envoy-wasm#530]
Hey. I am trying to build my own custom cpp wasm filter, to run in kubernetes and istio.
ISTIO_VERSION=1.5.0-beta.5

I used this guide: https://banzaicloud.com/blog/envoy-wasm-filter/
In short, I built the wasm-cpp-sdk, I then built the filter with sdk, put the filter's binary data in a configmap, and then added annotations to the deployment to mount the filter into istio-proxy. I can see that the filter was mounted successfully. For the last step I created an http EnvoyFilter that insert the wasm filter into the listener filter chain.

When I run this, I see an error: 'Failed to load WASM module due to a missing import: env.proxy_set_buffer_bytes'

Is anybody seen this issue before? Do you know what is the problem? I will add more data and logs if needed.

**Comment by jplevyak** [comment]
You have a mismatch between the SDK and the version of the proxy you are attempting to load the wasm module into.   The version of the SDK you are using is newer than the version of istio.  1.6 is out.  That version has make build_wasm which builds using a docker image specific to the version of istio you are going to link into.    PTAL
