### ISSUE TITLE
Select stats system via generic setProperty call

### ISSUE THREAD

**Issue by bianpengyuan** [envoyproxy/envoy-wasm#534]
We'd like ability to use different stats systems other than native envoy stats system, like opencensus. To select the system, `setProperty` could be used here to provide dynamic control.

Currently setProperty could only set property in filter state, we need to expand it to support setting generic properties, and in this case, the `metric_system` property. Envoy host env will decide the stats system to use for each metric definition based on value of the property.

**Comment by bianpengyuan** [comment]
@jplevyak @mandarjog @PiotrSikora @kyessenov

**Comment by mandarjog** [comment]
closing in favor of #536 `close()`
