### ISSUE TITLE
Wasm config error metrics

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy-wasm#553]
https://tinyurl.com/istio-wasm-failure-modes

We need the following counter to expose errors to the user.

wasm_config_error{error_type, filter_config_name, proxy_abi_version, proxy_version, wasm_vm}

###. error_type enum

* **Permanent read** error The bits to be loaded are not found, and the error is permanent. This will happen if the user provides an incorrect file or url location, or the reading process lacks permissions to read from the location.
* **Eventually consistent read** The user specifies the correct location but the bits are not available immediately. The read eventually succeeds in the vast majority of cases after retries. After a timeout this error becomes (1).
* **Invalid module** The Wasm module is invalid or it is compiled against an incorrect Wasm ABI version.
* **Invalid configuration** The Wasm module could be loaded, but the configuration provided to the module is invalid. VM config and Plugin config separately.

### filter_config_name
This should be config name specified in the XDS API. This will be the same name in Filte Discovery Service.

**Comment by mandarjog** [comment]
@jplevyak

**Comment by jplevyak** [comment]
There is a 1:1 relationship between the proxy_version and the proxy_abi_version.  Why do we need the latter ?

**Comment by mandarjog** [comment]
Ok, we can omit abi version for now.

**Comment by jplevyak** [comment]
Do we really need the "wasm_vm" ?  Getting that information is going to require extensive changes all over envoy-wasm
