### ISSUE TITLE
Singleton WASM services no longer available on Bootstrap object

### ISSUE THREAD

**Issue by gbrail** [envoyproxy/envoy-wasm#586]
Previously, one could put a "wasm_service" element at the top-level "bootstrap" object and use that to instantiate a WASM service that was not tied to a network or HTTP filter. This also supported a singleton pattern.

In the current master, this doesn't work -- there's no longer a "wasm_service" element on the bootstrap.proto.

Was this removed on purpose? Is this functionality coming back? Or do you recommend another way to implement some sort of shared state between WASM modules running in different threads on the same VM?

**Comment by bianpengyuan** [comment]
As far as I know, it is meant to be replaced by this generic bootstrap extension mechanism: https://github.com/envoyproxy/envoy/commit/8cb2958f29af3e45e87653356b6099bd3a4cbfbf Not sure if that is wired up with Wasm runtime or not.

**Comment by gbrail** [comment]
Makes sense -- thanks, and I'll stay tuned. I'm trying to prototype a
different kind of rate-limiting system and it'd be very helpful to be able
to maintain shared state between threads -- I feel that using queues to
communicate with a singleton WASM module would be cleaner and more
efficient than trying to use the existing shared-memory system for this.

**Comment by gbrail** [comment]
FWIW I'm back in business and was able to configure this:

bootstrap_extensions:
  - name: "envoy.bootstrap.wasm"
    typed_config: 
      "@type": type.googleapis.com/envoy.extensions.wasm.v3.WasmService
      singleton: true
      config:
        name: "TestService"
        vm_config:
          runtime: "envoy.wasm.runtime.v8"
          vm_id: "TestService"
          code: 
            local:
              filename: "target/wasm32-unknown-unknown/release/testservice.wasm"
          configuration: {}
