### ISSUE TITLE
Simplify gRPC ABI

### ISSUE THREAD

**Issue by gbrail** [envoyproxy/envoy-wasm#594]
I'm struggling to figure out how to use the proxy_grpc_call ABI function. Compiling the tree of .proto files necessary to create a GrpcService protobuf for passing to the ABI is difficult unless one is already building one's WASM module with Bazel, because the grpc_service.proto file imports 10 other files, and some of those import 10 more, and some of those come from different repos that are assembled at build time using Bazel, and so on.

I'd like to propose either a new ABI call, or a parameter to the existing one, that lets the caller pass simply the Envoy cluster name as a parameter instead of the serialized GrpcService protobuf. This method would only support the Envoy-native gRPC client and not the Google client but it'd be much easier for developers to use.

(An alternative is to just use proxy_http_call to make gRPC calls, which should work in theory for unary gRPC calls if the cluster is set up right.)

**Comment by PiotrSikora** [comment]
`proxy_grpc_call` should take an upstream name as the 1st argument, similarly to `proxy_http_call`. Passing protobufs over ABI boundary isn't very portable.

@jplevyak do you recall what's the reason for `grpc_service.proto` in the current implementation? Is it because we needed to use Google gRPC instead of Envoy gRPC?

**Comment by gbrail** [comment]
Oh yes, this would be a great usability improvement -- I ended up using
http_call in one bit of code rather than grpc_call for this reason.

BTW it's worse than just having to generate a proto in the WASM -- the
proto comes from the Envoy source code and pulls in 10 imports, each of
which pull in 10 other imports. Basically, I don't see how one generates
proto stubs to even generate the proto unless you are building with Bazel
and have the Envoy source repo handy.

I assume this is all necessary to support the Google gRPC client.

One alternative would be to have a variant of "http_call" that just takes
an upstream name, and is limited to the "Envoy" gRPC client only.

**Comment by mandarjog** [comment]
@bianpengyuan we are using the full grpc service proto in stack driver filters, right? Can that use an upstream cluster?
