### ISSUE TITLE
Question: Where is proxy_log defined

### ISSUE THREAD

**Issue by mrpre** [envoyproxy/envoy-wasm#66]
I know it's not a good question but I'm pretty curious about it.  

I find the wasm example use logxxx function
https://github.com/envoyproxy/envoy-wasm/blob/f66e557b6e787043e9efde5cfcd88afdce0b9408/examples/wasm/envoy_filter_http_wasm_example.cc#L34

which is defined at
https://github.com/envoyproxy/envoy-wasm/blob/bbbe0564af5c3fe932942744ac8c76353277fc0c/api/wasm/cpp/proxy_wasm_impl.h#L26-L28

So I'm curious where `proxy_log` is defined and as I know the log function finally should be implemented at host env and where is the final log function defined and imported( for wasm env using) ?

**Comment by PiotrSikora** [comment]
`proxy_log` is provided by the host environment (i.e. Envoy).

It's defined here (sorry about the unsearchable macros!):
https://github.com/envoyproxy/envoy-wasm/blob/f66e557b6e787043e9efde5cfcd88afdce0b9408/source/extensions/common/wasm/wasm.cc#L1593-L1598

its handler is implemented here:
https://github.com/envoyproxy/envoy-wasm/blob/f66e557b6e787043e9efde5cfcd88afdce0b9408/source/extensions/common/wasm/wasm.cc#L740-L744

and the actual logging in performed here:
https://github.com/envoyproxy/envoy-wasm/blob/f66e557b6e787043e9efde5cfcd88afdce0b9408/source/extensions/common/wasm/wasm.cc#L1263-L1286

Hope this helps!

**Comment by mrpre** [comment]
Roger that !
