### ISSUE TITLE
WASM: Provide an api to force recompute routes

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy-wasm#75]
lua filter will automagically flush route cache when a header changes.
1. WASM should add a new API `recompute_routes`   or `internal_redirect` which should flush route cache internally.
2. It should also discard the metadata cache in the sandbox.

**Comment by jplevyak** [comment]
Which types of metadata should be cached?  Request/Response/RequestRoute/ResponseRoute/Log/Node?

Currently I am caching on Metadata::Node.   I expect that Log should also be cached.  What about the others ?  Probably not Request/Response, but RequestRoute/ResponseRoute?

**Comment by PiotrSikora** [comment]
Per previous discussion, let's drop the cache for the time being, since if we crossed the host boundary, then we're not really saving anything.

`clearRouteCache()` was added in #79, so marking this as fixed.
