### ISSUE TITLE
Switch Emscripten from "fastcomp" to "upstream"

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy-wasm#77]

**Comment by jplevyak** [comment]
When attempting to build the protobuf libraries for wasm, emsdk 1.38.39 fails with:


/bin/bash ../libtool  --tag=CXX   --mode=compile /home/jplev_google_com/emsdk/upstream/emscripten/em++ -DHAVE_CONFIG_H -I. -I..    -pthread -DHAVE_PTHREAD=1  -Wall -Wno-sign-compare -O2 -g -std=c++11 -DNDEBUG -MT google/protobuf/arena.lo -MD -MP -MF $depbase.Tpo -c -o google/protobuf/arena.lo google/protobuf/arena.cc &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  /home/jplev_google_com/emsdk/upstream/emscripten/em++ -DHAVE_CONFIG_H -I. -I.. -pthread -DHAVE_PTHREAD=1 -Wall -Wno-sign-compare -O2 -g -std=c++11 -DNDEBUG -MT google/protobuf/arena.lo -MD -MP -MF google/protobuf/.deps/arena.Tpo -c google/protobuf/arena.cc  -fPIC -DPIC -o google/protobuf/.libs/arena.o
fatal error: error in backend: Cannot select: t24: i32 = GlobalTLSAddress<%"struct.google::protobuf::internal::ArenaImpl::ThreadCache"* @_ZN6google8protobuf8internal9ArenaImpl13thread_cache_E> 0, google/protobuf/arena.cc:355:18 @[ google/protobuf/arena.cc:79:9 ]
In function: _ZN6google8protobuf8internal9ArenaImpl4InitEv
clang-9: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 9.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 667ca68bdef7673d84106c69a8ef0bd73c58f95e)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/jplev_google_com/emsdk/upstream/bin
clang-9: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-9: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-9: note: diagnostic msg: /tmp/arena-ea21b6.cpp
clang-9: note: diagnostic msg: /tmp/arena-ea21b6.sh
clang-9: note: diagnostic msg: 

********************
shared:ERROR: compiler frontend failed to generate LLVM bitcode, halting
