### ISSUE TITLE
WASM: setMetadata / getMetadata calls should return error/bool

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy-wasm#88]
Most/all functions defined in wasm_api_impl.h are `inline void` 
They should be `inline bool` so they can indicate an error.
At present `source/extensions/common/wasm/wasm.cc  Context::setMetadataStruct`
parses metadata and silently drops error.
All these functions should return errors/and or log error details at debug level.

**Comment by jplevyak** [comment]
Just to clarify getMetadata returns "" if the data is missing or if it can't be serialized and you want to differentiate those cases?

**Comment by mandarjog** [comment]
Setmetadata is void though, that is where I had trouble.

**Comment by jplevyak** [comment]
https://github.com/envoyproxy/envoy-wasm/pull/99
