### ISSUE TITLE
Migrate to new stats APIs

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy-wasm#93]
https://github.com/envoyproxy/envoy/pull/6475 added:
- `counterFromStatName()`,
- `gaugeFromStatName()`,
- `histogramFromStatName()`.

Example migration (rate limit filter) in https://github.com/envoyproxy/envoy/pull/7573.

**Comment by jmarantz** [comment]
+1 to this -- I am hoping to remove the whitelist after fixing the handful of remaining direct calls to counter() et al.

**Comment by jmarantz** [comment]
I am close to issuing a PR that removes the check_format whitelist. What's the status on resolving this?

**Comment by jplevyak** [comment]
Working on it now.

**Comment by jplevyak** [comment]
https://github.com/envoyproxy/envoy-wasm/pull/121
